### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by mikkimichaelis** [oktadeveloper/okta-ionic-auth-example#12]
> git clone https://github.com/oktadeveloper/okta-ionic-auth-example.git
> cd okta-ionic-auth-example

> node -v
v12.20.2

> npm -v
6.14.11

> npm install
...
14 warnings and 7 errors generated.
make: *** [Release/obj.target/binding/src/binding.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/mikki/Projects/okta-ionic-auth-example/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
gyp ERR! System Darwin 20.3.0
gyp ERR! command "/Users/mikki/.nvm/versions/node/v12.20.2/bin/node" "/Users/mikki/Projects/okta-ionic-auth-example/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/mikki/Projects/okta-ionic-auth-example/node_modules/node-sass
gyp ERR! node -v v12.20.2
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
Build failed with error code: 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 install: `node install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.5.3 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.5.3 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by mraible** [comment]
You are correct.

Please see https://developer.okta.com/blog/2020/09/21/ionic-apple-google-signin for an updated version. If we updated all our blog posts (and repos) to the latest releases, we'd never have time to write new posts!

If you *really* want to get this example working, here's how:

1. Install npm-check-updates:
      npm i -g npm-check-updates
2. Run `ncu -u` to update all dependencies to the latest versions.
3. Run `npm install`

This solves the `npm install` issue, but then you'll see lots of compile errors. That's why I recommend using the tutorial mentioned above.

**Comment by mikkimichaelis** [comment]
Thank you.
